# Generated by Django 5.1.6 on 2025-03-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name',
                 models.CharField(
                    max_length=200,
                    unique=True,
                    verbose_name='Название'
                 )),
                ('legal_address',
                 models.TextField(verbose_name='Юридический адрес')),
                (
                    'physical_address',
                    models.TextField(verbose_name='Физический адрес')
                ),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Дата создания'
                )),
                ('start_time',
                 models.DateTimeField(verbose_name='Время начала')),
                ('end_time',
                 models.DateTimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[
                    ('confirmed', 'Подтверждена'),
                    ('pending', 'Ожидает'),
                    ('started', 'Начата'),
                    ('completed', 'Завершена'),
                    ('paid', 'Оплачена')
                ], default='pending', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
        migrations.CreateModel(
            name='DoctorsSpecialityInClinics',
            fields=[
                ('id',
                 models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('specialty',
                 models.CharField(
                    max_length=100,
                    verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
    ]
