# Generated by Django 5.1.6 on 2025-03-05 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics_work_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='patient_at_consultation',
                to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='doctorsspecialityinclinics',
            name='clinic',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='clinic',
                to='clinics_work_app.clinic',
                verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='doctorsspecialityinclinics',
            name='doctor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='doctor_at_clinic',
                to=settings.AUTH_USER_MODEL, verbose_name='Доктор'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_in_clinics',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='doctor_at_consultation',
                to='clinics_work_app.doctorsspecialityinclinics',
                verbose_name='Доктор'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorsspecialityinclinics',
            unique_together={('doctor', 'clinic', 'specialty')},
        ),
    ]
