# Generated by Django 5.1.6 on 2025-03-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_work_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorsspecialityinclinics',
            options={
                'verbose_name': 'Специализация доктора в клинике',
                'verbose_name_plural': 'Специализации докторов в клинике'},
        ),
    ]
